In [ ]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

In [12]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd

# creates the client
woc = WocMapsRemote(base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
    "arnaudon/netSALT",
    "PythonOT/POT",
    "blegat/SwitchOnSafety.jl",
    "connectomicslab/connectomemapper3",
    "BBN-Q/Auspex",
    "vsamy/Copra",
    "havakv/pycox",
    "seung-lab/igneous",
    "salan668/FAE",
    "matsengrp/transport",
]
list_df_commits = []
for prj in projects:
    # Convert GitHub repository names to WoC V2412 project names
    prj = prj.lower().replace("/", "_", 2)
    commits = woc.get_values("p2c", prj)
    df = pd.DataFrame(commits, columns=["sha1"])
    df["project"] = prj
    list_df_commits.append(df)
df = pd.concat(list_df_commits)
# perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv("df_commits.csv")
df.head(1)

                                       sha1           project
0  005227b76ce4b178c1e5cbf5d4ff2a92fed36456  arnaudon_netsalt

In [16]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

 34%|███▍      | 579/1710 [10:17<20:27,  1.09s/it]

Got Errors {'4bb179ca211950c8b1499f8e78049b6e700f7ebf': 'Key 4bb179ca211950c8b1499f8e78049b6e700f7ebf not found in /da5_fast/All.sha1c/commit_75.tch'}

 35%|███▍      | 591/1710 [10:30<20:07,  1.08s/it]

Got Errors {'8738228d90a260a8b9b7ab99389bbb0551dfb2e2': 'Key 8738228d90a260a8b9b7ab99389bbb0551dfb2e2 not found in /da5_fast/All.sha1c/commit_7.tch'}

 69%|██████▉   | 1184/1710 [21:05<09:27,  1.08s/it]

Got Errors {'81f9107b25a0c6fed70e82e88f3d600f9ff97b7c': 'Key 81f9107b25a0c6fed70e82e88f3d600f9ff97b7c not found in /da5_fast/All.sha1c/commit_1.tch'}

 72%|███████▏  | 1223/1710 [21:47<08:46,  1.08s/it]

Got Errors {'9c64ebf5ae5de65fc7de9a9502cbe62db0706c21': 'Key 9c64ebf5ae5de65fc7de9a9502cbe62db0706c21 not found in /da5_fast/All.sha1c/commit_28.tch'}

 74%|███████▍  | 1262/1710 [22:29<08:04,  1.08s/it]

Got Errors {'b796e3ce45dd674740a2c635daf693c0d560fa6e': 'Key b796e3ce45dd674740a2c635daf693c0d560fa6e not found in /da5_fast/All.sha1c/commit_55.tch'}

 79%|███████▉  | 1354/1710 [24:09<06:23,  1.08s/it]

Got Errors {'f9de4f0baf178cf3aaf51a00d2c8dc4ad5057cba': 'Key f9de4f0baf178cf3aaf51a00d2c8dc4ad5057cba not found in /da5_fast/All.sha1c/commit_121.tch'}

 80%|███████▉  | 1362/1710 [24:18<06:14,  1.08s/it]

Got Errors {'019da08a7d21bd6939157690826b502041031644': 'Key 019da08a7d21bd6939157690826b502041031644 not found in /da5_fast/All.sha1c/commit_1.tch', '037bcbcac4fd5da8c9c3ddb42e507c1cbd7591eb': 'Key 037bcbcac4fd5da8c9c3ddb42e507c1cbd7591eb not found in /da5_fast/All.sha1c/commit_3.tch'}

 80%|███████▉  | 1364/1710 [24:20<06:13,  1.08s/it]

Got Errors {'11e6b309b2246e6cd61a5d6925115fcd20403d14': 'Key 11e6b309b2246e6cd61a5d6925115fcd20403d14 not found in /da5_fast/All.sha1c/commit_17.tch', '128620ae25bb7f0246e8f05b84f90308c4701096': 'Key 128620ae25bb7f0246e8f05b84f90308c4701096 not found in /da5_fast/All.sha1c/commit_18.tch', '1543804daa65f9c7aecfbb0fe605ebfeefe6733b': 'Key 1543804daa65f9c7aecfbb0fe605ebfeefe6733b not found in /da5_fast/All.sha1c/commit_21.tch'}

 80%|███████▉  | 1365/1710 [24:21<06:13,  1.08s/it]

Got Errors {'18505ea00049417542218e948cd497022c160fa9': 'Key 18505ea00049417542218e948cd497022c160fa9 not found in /da5_fast/All.sha1c/commit_24.tch'}

 80%|███████▉  | 1366/1710 [24:22<06:11,  1.08s/it]

Got Errors {'207ad33ba9f37e0552dd074788b419174bd68984': 'Key 207ad33ba9f37e0552dd074788b419174bd68984 not found in /da5_fast/All.sha1c/commit_32.tch', '211f7f4e585818807d0bb148951ebd0e91a0eac7': 'Key 211f7f4e585818807d0bb148951ebd0e91a0eac7 not found in /da5_fast/All.sha1c/commit_33.tch'}

 80%|████████  | 1370/1710 [24:26<06:08,  1.08s/it]

Got Errors {'3e480da1fcbb7be6f31850ccb52ed7f444226094': 'Key 3e480da1fcbb7be6f31850ccb52ed7f444226094 not found in /da5_fast/All.sha1c/commit_62.tch', '3eef7d3d567113987cda8fb620b14ffa2fcd99ba': 'Key 3eef7d3d567113987cda8fb620b14ffa2fcd99ba not found in /da5_fast/All.sha1c/commit_62.tch'}

 80%|████████  | 1371/1710 [24:28<06:06,  1.08s/it]

Got Errors {'407f20e2ffd216ac604b1e8e0a0ebf0cfe8b9b66': 'Key 407f20e2ffd216ac604b1e8e0a0ebf0cfe8b9b66 not found in /da5_fast/All.sha1c/commit_64.tch'}

 80%|████████  | 1372/1710 [24:29<06:07,  1.09s/it]

Got Errors {'46de32152124dbf11dc7176c72073f91b2ec6825': 'Key 46de32152124dbf11dc7176c72073f91b2ec6825 not found in /da5_fast/All.sha1c/commit_70.tch'}

 80%|████████  | 1373/1710 [24:30<06:05,  1.09s/it]

Got Errors {'4d4eb97ef7f9ed2f5c72bc0fe1608be214bf1842': 'Key 4d4eb97ef7f9ed2f5c72bc0fe1608be214bf1842 not found in /da5_fast/All.sha1c/commit_77.tch', '4e5dcf862b0183dfbb7d92df3cd47905083ce14d': 'Key 4e5dcf862b0183dfbb7d92df3cd47905083ce14d not found in /da5_fast/All.sha1c/commit_78.tch'}

 80%|████████  | 1374/1710 [24:31<06:05,  1.09s/it]

Got Errors {'4f8f925a2588fcaeec35632ad9f0bfc6037fd42e': 'Key 4f8f925a2588fcaeec35632ad9f0bfc6037fd42e not found in /da5_fast/All.sha1c/commit_79.tch'}

 80%|████████  | 1375/1710 [24:32<06:04,  1.09s/it]

Got Errors {'602028603ba780eb12c1a45d3c8941dfb2e7b2ae': 'Key 602028603ba780eb12c1a45d3c8941dfb2e7b2ae not found in /da5_fast/All.sha1c/commit_96.tch', '621c215b77b84c7c4c9d00ad2a05b97e8295ff74': 'Key 621c215b77b84c7c4c9d00ad2a05b97e8295ff74 not found in /da5_fast/All.sha1c/commit_98.tch'}

 80%|████████  | 1376/1710 [24:33<06:02,  1.09s/it]

Got Errors {'64bf1eef28c0fd10b801fd8dafba1c340ba5388d': 'Key 64bf1eef28c0fd10b801fd8dafba1c340ba5388d not found in /da5_fast/All.sha1c/commit_100.tch'}

 81%|████████  | 1381/1710 [24:38<05:55,  1.08s/it]

Got Errors {'83bf15d2e33731c2c86eb6c97b3e78cd10c143bf': 'Key 83bf15d2e33731c2c86eb6c97b3e78cd10c143bf not found in /da5_fast/All.sha1c/commit_3.tch', '8911adb34b1b1af8613fd0587d5b02e297756505': 'Key 8911adb34b1b1af8613fd0587d5b02e297756505 not found in /da5_fast/All.sha1c/commit_9.tch'}

 81%|████████  | 1382/1710 [24:39<05:55,  1.08s/it]

Got Errors {'91be9df02cd838a60154d3e05892a6e8091df745': 'Key 91be9df02cd838a60154d3e05892a6e8091df745 not found in /da5_fast/All.sha1c/commit_17.tch'}

 81%|████████  | 1383/1710 [24:41<05:53,  1.08s/it]

Got Errors {'9d1642ea564ceea01e9d66716f97be6921de908f': 'Key 9d1642ea564ceea01e9d66716f97be6921de908f not found in /da5_fast/All.sha1c/commit_29.tch'}

 81%|████████  | 1385/1710 [24:43<05:51,  1.08s/it]

Got Errors {'accbac7389f90f3d98e21e15da7639a3df6ab0f7': 'Key accbac7389f90f3d98e21e15da7639a3df6ab0f7 not found in /da5_fast/All.sha1c/commit_44.tch', 'b26d8b9c9dad46d52953bb4e9553d37d00474484': 'Key b26d8b9c9dad46d52953bb4e9553d37d00474484 not found in /da5_fast/All.sha1c/commit_50.tch'}

 81%|████████  | 1388/1710 [24:46<06:02,  1.12s/it]

Got Errors {'c344ff8dc231a18791f65147a7c526d7c1f92df2': 'Key c344ff8dc231a18791f65147a7c526d7c1f92df2 not found in /da5_fast/All.sha1c/commit_67.tch'}

 81%|████████  | 1389/1710 [24:47<05:57,  1.11s/it]

Got Errors {'c62d41c469434872402cb6e9487383cae14c9374': 'Key c62d41c469434872402cb6e9487383cae14c9374 not found in /da5_fast/All.sha1c/commit_70.tch'}

 81%|████████▏ | 1390/1710 [24:48<05:52,  1.10s/it]

Got Errors {'cc8ca656002ea541328ba35dd532633cf0fce5c0': 'Key cc8ca656002ea541328ba35dd532633cf0fce5c0 not found in /da5_fast/All.sha1c/commit_76.tch'}

 81%|████████▏ | 1392/1710 [24:50<05:47,  1.09s/it]

Got Errors {'d52de8c39c2c425e6fdad6e94806d97f8a5aa941': 'Key d52de8c39c2c425e6fdad6e94806d97f8a5aa941 not found in /da5_fast/All.sha1c/commit_85.tch', 'd7b98068c52416820348f035a00183460e15cea7': 'Key d7b98068c52416820348f035a00183460e15cea7 not found in /da5_fast/All.sha1c/commit_87.tch'}

 87%|████████▋ | 1494/1710 [26:41<03:54,  1.09s/it]

Got Errors {'4651c343bf3db6d62e565d621c2575d9380d31ae': 'Key 4651c343bf3db6d62e565d621c2575d9380d31ae not found in /da5_fast/All.sha1c/commit_70.tch'}

 93%|█████████▎| 1593/1710 [28:29<02:06,  1.08s/it]

Got Errors {'cef18adda47feaefcb78352fed43097e99e28112': 'Key cef18adda47feaefcb78352fed43097e99e28112 not found in /da5_fast/All.sha1c/commit_78.tch'}

 94%|█████████▍| 1608/1710 [28:46<01:51,  1.10s/it]

Got Errors {'e3deed1e16eeff182bfe848e0861f553103cc8df': 'Key e3deed1e16eeff182bfe848e0861f553103cc8df not found in /da5_fast/All.sha1c/commit_99.tch'}

 94%|█████████▍| 1610/1710 [28:48<01:48,  1.09s/it]

Got Errors {'e5a29e8b97984a5464a62714a0fec119744df896': 'Key e5a29e8b97984a5464a62714a0fec119744df896 not found in /da5_fast/All.sha1c/commit_101.tch'}

 96%|█████████▋| 1646/1710 [29:27<01:09,  1.08s/it]

Got Errors {'580154d132f5d0f32cb763bcdcc37b8a9a3debcd': 'Key 580154d132f5d0f32cb763bcdcc37b8a9a3debcd not found in /da5_fast/All.sha1c/commit_88.tch'}

100%|██████████| 1710/1710 [30:36<00:00,  1.07s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,005227b76ce4b178c1e5cbf5d4ff2a92fed36456,276c366100a853ca08d7416179eeafaeb479666a,[048e05847a3c5ca2281cb7ba32bf1a8801d220bc],alexis arnaudon <alexis.arnaudon@epfl.ch>,1581848668,+0100,alexis arnaudon <alexis.arnaudon@epfl.ch>,1581848668,+0100,mode trajectories\n,005227b76ce4b178c1e5cbf5d4ff2a92fed36456,arnaudon_netsalt
1,0085f39eab2321e4b71da2cf97f286d79dcb4920,6797a539d79b970b158a2c32211976826bcc2579,[fcc8dfc53b8dc86a97457a247ab47861de52ff59],arnaudon <alexis.arnaudon@epfl.ch>,1646322150,+0100,arnaudon <alexis.arnaudon@epfl.ch>,1646322150,+0100,more\n,0085f39eab2321e4b71da2cf97f286d79dcb4920,arnaudon_netsalt

In [17]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '005227b76ce4b178c1e5cbf5d4ff2a92fed36456', 'tree': '276c366100a853ca08d7416179eeafaeb479666a', 'parent': ['048e05847a3c5ca2281cb7ba32bf1a8801d220bc'], 'author': 'alexis arnaudon <alexis.arnaudon@epfl.ch>', 'author_time': 1581848668, 'author_tz': '+0100', 'committer': 'alexis arnaudon <alexis.arnaudon@epfl.ch>', 'committer_time': 1581848668, 'committer_tz': '+0100', 'message': 'mode trajectories\n'}

In [18]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [19]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,matsengrp_transport,005227b76ce4b178c1e5cbf5d4ff2a92fed36456,alexis arnaudon <alexis.arnaudon@epfl.ch>,1581848668,mode trajectories\n

In [20]:
#mode a means append, so you have all your projects in the same file
yournetid='pshu'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github